In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Load Datasets
train=pd.read_csv("/content/drive/My Drive/Colab Notebooks/Zimnat Insurance Recommendation Challenge/Train.csv")
test=pd.read_csv("/content/drive/My Drive/Colab Notebooks/Zimnat Insurance Recommendation Challenge/Test.csv")
sub=pd.read_csv("/content/drive/My Drive/Colab Notebooks/Zimnat Insurance Recommendation Challenge/SampleSubmission.csv")

In [ ]:
train.head()

        ID join_date sex marital_status  ...  JZ9D J9JW GHYX ECY3
0  4WKQSBB  1/2/2019   F              M  ...     0    0    0    0
1  CP5S02H  1/6/2019   F              M  ...     0    0    0    0
2  2YKDILJ  1/6/2013   M              U  ...     0    0    0    1
3  2S9E81J  1/8/2019   M              M  ...     0    0    0    0
4  BHDYVFT  1/8/2019   M              M  ...     1    1    0    0

[5 rows x 29 columns]

In [ ]:
test.head()

        ID  join_date sex marital_status  ...  JZ9D J9JW GHYX ECY3
0  F86J5PC  1/12/2018   M              M  ...     0    0    0    0
1  H6141K3  1/10/2019   M              M  ...     0    0    0    0
2  RBAYUXZ   1/1/2020   F              W  ...     0    0    0    0
3  KCBILBQ   1/2/2019   M              M  ...     0    0    0    0
4  LSEC1ZJ   1/2/2020   F              M  ...     1    0    0    0

[5 rows x 29 columns]

In [ ]:
#Filter out product codes for train Data
train_productcode =train[['P5DA', 'RIBP', '8NN1',
       '7POT', '66FJ', 'GYSR', 'SOP4', 'RVSZ', 'PYUQ', 'LJR9', 'N2MW', 'AHXO',
       'BSTQ', 'FM3X', 'K6QO', 'QBOL', 'JWFN', 'JZ9D', 'J9JW', 'GHYX', 'ECY3']]

#Filter out product codes for test Data
test_productcode =test[['P5DA', 'RIBP', '8NN1',
       '7POT', '66FJ', 'GYSR', 'SOP4', 'RVSZ', 'PYUQ', 'LJR9', 'N2MW', 'AHXO',
       'BSTQ', 'FM3X', 'K6QO', 'QBOL', 'JWFN', 'JZ9D', 'J9JW', 'GHYX', 'ECY3']]

In [ ]:
#check shape of train and test dataset
print(train.shape, test.shape)

(29132, 29) (10000, 29)

#Convert product Code columns into one columns

In [ ]:
##basically it customers*productcode
train = train.melt(id_vars=train.columns[:8], value_vars=train_productcode, var_name = "PCODE", value_name="Label" )

#basically it customers*productcode
test = test.melt(id_vars=test.columns[:8], value_vars=test_productcode, var_name = "PCODE", value_name="Label" )

In [ ]:
#After Converting product Code columns into one columns the shape has changed
print(train.shape, test.shape)

(611772, 11) (210000, 11)

In [ ]:
#Create X variable That would be used to ID and PCODE in train data
train['join']='x'

#Create X variable That would be used to ID and PCODE in test data
test['join']='x'

In [ ]:
train.head()

        ID join_date sex  ... PCODE  Label join
0  4WKQSBB  1/2/2019   F  ...  P5DA      0    x
1  CP5S02H  1/6/2019   F  ...  P5DA      0    x
2  2YKDILJ  1/6/2013   M  ...  P5DA      0    x
3  2S9E81J  1/8/2019   M  ...  P5DA      0    x
4  BHDYVFT  1/8/2019   M  ...  P5DA      0    x

[5 rows x 11 columns]

In [ ]:
#Combine ID with PCODE 
train['ID X PCODE'] =train['ID'] + ' X ' + train['PCODE']
test['ID X PCODE'] =test['ID'] + ' X ' + test['PCODE']

In [ ]:
test.head()

        ID  join_date sex marital_status  ...  PCODE Label join      ID X PCODE
0  F86J5PC  1/12/2018   M              M  ...   P5DA     0    x  F86J5PC X P5DA
1  H6141K3  1/10/2019   M              M  ...   P5DA     0    x  H6141K3 X P5DA
2  RBAYUXZ   1/1/2020   F              W  ...   P5DA     0    x  RBAYUXZ X P5DA
3  KCBILBQ   1/2/2019   M              M  ...   P5DA     0    x  KCBILBQ X P5DA
4  LSEC1ZJ   1/2/2020   F              M  ...   P5DA     0    x  LSEC1ZJ X P5DA

[5 rows x 12 columns]

In [ ]:
test=test[['ID','join_date','sex','marital_status','birth_year','branch_code','occupation_code','occupation_category_code','PCODE','ID X PCODE','Label']]
test.head()

        ID  join_date sex  ... PCODE      ID X PCODE Label
0  F86J5PC  1/12/2018   M  ...  P5DA  F86J5PC X P5DA     0
1  H6141K3  1/10/2019   M  ...  P5DA  H6141K3 X P5DA     0
2  RBAYUXZ   1/1/2020   F  ...  P5DA  RBAYUXZ X P5DA     0
3  KCBILBQ   1/2/2019   M  ...  P5DA  KCBILBQ X P5DA     0
4  LSEC1ZJ   1/2/2020   F  ...  P5DA  LSEC1ZJ X P5DA     0

[5 rows x 11 columns]

In [ ]:
train=train[['ID','join_date','sex','marital_status','birth_year','branch_code','occupation_code','occupation_category_code','PCODE','ID X PCODE','Label']]
train.head()

        ID join_date sex  ... PCODE      ID X PCODE Label
0  4WKQSBB  1/2/2019   F  ...  P5DA  4WKQSBB X P5DA     0
1  CP5S02H  1/6/2019   F  ...  P5DA  CP5S02H X P5DA     0
2  2YKDILJ  1/6/2013   M  ...  P5DA  2YKDILJ X P5DA     0
3  2S9E81J  1/8/2019   M  ...  P5DA  2S9E81J X P5DA     0
4  BHDYVFT  1/8/2019   M  ...  P5DA  BHDYVFT X P5DA     0

[5 rows x 11 columns]

In [ ]:
#save new train dataframe to csv
train.to_csv('/content/drive/My Drive/Colab Notebooks/Zimnat Insurance Recommendation Challenge/train_data.csv')

#save new test dataframe to csv
test.to_csv('/content/drive/My Drive/Colab Notebooks/Zimnat Insurance Recommendation Challenge/test_data.csv')